In [1]:
# See here for more help:

# http://stackoverflow.com/questions/33385898/how-to-include-constraint-to-scipy-nnls-function-solution-so-that-it-sums-to-1

import numpy as np

from scipy.optimize import minimize

from scipy.optimize import nnls

# #Define problem

# A = np.array([[60, 90, 120],

# [30, 120, 90]])

# b = np.array([67.5, 60])

# #Use nnls to get initial guess

# x0, rnorm = nnls(A,b)

# #Define minimisation function

# def fn(x, A, b):

# return np.linalg.norm(A.dot(x) - b)

# #Define constraints and bounds

# cons = {'type': 'eq', 'fun': lambda x: np.sum(x)-1}

# bounds = [[0., None],[0., None],[0., None]]

# #Call minimisation subject to these values

# minout = minimize(fn, x0, args=(A, b), method='SLSQP',bounds=bounds,constraints=cons)

# x = minout.x

# print(x,x.sum(),fn(x,A,b))

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days


In [6]:
import pandas as pd
df_e = pd.read_csv('foodweb/20160907_exomet_neg1topos1_midlate.csv')
df_m = pd.read_csv('foodweb/20160907_microbes_abundance_midlate.csv')
df_p = pd.read_csv('foodweb/20160907_porewater_metabolites_midlate.csv')

In [7]:
df_e.sort('metabolite',inplace=True)
df_e.head()

metabolite  rplo 1 (mv)  rplo 2 (D1B51)  rplo 7 (L1B44)  \
14     (3-methyladenine)      1.00000        0.000000        0.000000   
3     (N6-acetyl-lysine)      1.00000        1.000000       -0.489020   
12       (ergothioneine)     -0.27626        0.131433        0.023065   
19  4-guanidinobutanoate      1.00000        0.535720       -0.058116   
15       7-methyladenine      1.00000        0.000000        0.000000   

    rplo 60 (L2B47)  
14         0.000000  
3          1.000000  
12         0.000018  
19        -0.226441  
15         0.000000

In [8]:
df_m.head()

Unnamed: 0     3 min      9 hr     18 hr     42 hr   49.5 hr
0      rplo 1 (mv)  0.922379  0.294431  0.173530  0.043212  0.062950
1   rplo 2 (D1B51)  0.000000  0.661070  0.774794  0.627533  0.657374
2   rplo 7 (L1B44)  0.077621  0.044499  0.037233  0.089101  0.223022
3  rplo 60 (L2B47)  0.000000  0.000000  0.014442  0.240153  0.056655

In [9]:
df_p.sort('Unnamed: 0',inplace=True)
df_p.head()

Unnamed: 0  3 min      9 hr     18 hr     42 hr   49.5 hr
0     (3-methyladenine)      0  1.000000  0.390916  0.232349  0.098514
2    (N6-acetyl-lysine)      0  1.000000  0.322569  0.503559  0.113778
1       (ergothioneine)      1  0.200588  0.068470  0.000000  0.004760
3  4-guanidinobutanoate      0  0.495204  0.338313  1.000000  0.186521
4       7-methyladenine      0  0.254461  0.263737  0.940813  1.000000

In [10]:
M = df_m[['3 min','9 hr','18 hr','42 hr','49.5 hr']].as_matrix()
E = df_e[['rplo 1 (mv)','rplo 2 (D1B51)','rplo 7 (L1B44)','rplo 60 (L2B47)']].as_matrix()
P = df_p[['3 min','9 hr','18 hr','42 hr','49.5 hr']].as_matrix()

In [11]:
T = E.dot(M)

In [12]:
T.shape

(32, 5)

In [17]:
print T

[[ 0.92237857  0.29443079  0.17353041  0.04321224  0.06294964]
 [ 0.88442016  0.93374004  0.94455867  0.86732634  0.66791643]
 [-0.25302597  0.00657363  0.05475337  0.07260045  0.07415551]
 [ 0.91786751  0.6459935   0.58316932  0.31983595  0.38932826]
 [ 0.92237857  0.29443079  0.17353041  0.04321224  0.06294964]
 [ 0.92237857  0.29443079  0.17353041  0.04321224  0.06294964]
 [ 0.93416494  0.63240642  0.57459609  0.49111245  0.45447971]
 [ 0.86456076  0.62767301  0.56540115  0.16146391  0.2226714 ]
 [ 0.87913485  0.1404426   0.00224537 -0.1144164  -0.18631605]
 [ 0.85932985 -0.06758586 -0.24755933 -0.48674427 -0.47722378]
 [ 0.30338117  0.2251433   0.21330046  0.25314507  0.22431044]
 [-0.8485733  -0.56240583 -0.50998019 -0.52667367 -0.5592214 ]
 [ 0.96226495  0.01208748 -0.15963033 -0.11057972 -0.10468501]
 [-0.14715301 -0.20330946 -0.21465986 -0.23260775 -0.22044921]
 [-0.7858888  -0.91047781 -0.9348805  -0.93647966 -0.87581249]
 [-0.84023672 -0.87206945 -0.87870685 -0.89194697 -0.88

In [18]:
from matplotlib import pyplot as plt
f = plt.figure(figsize = (18,20))
for i in range(32):
    plt.subplot(4,8,i+1)
    plt.plot(T[i,:])
    plt.plot(P[i,:])
plt.tight_layout()
plt.show()

In [ ]:
# x,resid,rank,s = np.linalg.lstsq(P,E.dot(M))
# x

In [ ]:
# # minout = minimize(fn, x0, args=(A, b), method='SLSQP',bounds=bounds,constraints=cons)
# # #Define minimisation function
# def fn(P, E, M, x):
# m1 = E.dot(M)
# m1.x
# return np.linalg.norm(E.dot(M) - P)
3
# # #Define constraints and bounds
# # cons = {'type': 'eq', 'fun': lambda x: np.sum(x)-1}
# # bounds = [[0., None],[0., None],[0., None]]